# Generated by Django 3.2.3 on 2021-06-01 09:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_posts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='postVideos'),
        ),
    ]
