# Generated by Django 3.2.3 on 2021-06-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_posts_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='video',
        ),
    ]
